language: node_js
node_js: stable

# S: Build Lifecycle

before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
  - npm install -g hexo
  - npm install -g hexo-cli
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm install hexo-deployer-git --save
  - hexo g
  - hexo d

after_script:
  - cd ./public
  - git init
  - git config user.name "tanglihong"
  - git config user.email "18202823176@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push origin
# E: Build LifeCycle

branches:
  only:
    - raw
env:
 global:
   - GH_REF: github.com/tanglihong/tanglihong.github.io.git